server:
  port: 8081

logging:
  level:
    root: debug

## Refs.
## https://www.keycloak.org/docs/latest/securing_apps/index.html#_spring_boot_adapter
keycloak:
  realm: kc4-boot2
  auth-server-url: http://localhost:8080/auth
  ssl-required: external
  resource: kc4-boot2-client
